### ISSUE TITLE
how to actually RUN this thing?

### ISSUE THREAD

**Issue by logiczny** [PLUTEX/pve_balance#2]
Hi,
Where is a code to execute (which file exactly), or the executable itself?
I can see that this is coded 100% in python, but can't tell what file to run.

**Comment by jplitza** [comment]
If you install this, e.g. via `pip install git+https://github.com/PLUTEX/pve_balance` it will simply install a wrapper script `pve_balance` into your `$PATH`. Alternately, you should be able to execute `python3 -m pve_blanace` without installation after checkout out and cd'ing into the checkout.

**Comment by logiczny** [comment]
I finally made it via 
`pip3 install .`
I'm not familiar with python yet.

Maybe you should consider adding this info to the README file? 
There's probably more noobs like me :)

Thanks for the support!
